NoteApp/Controllers/HomeController.cs
using NoteApp.Exceptions;
using NoteApp.Models;
using NoteApp.Services;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace NoteApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly INotesService _notesService;
        private readonly ICheckRoleService _checkRoleService;        

        public HomeController(INotesService notesService, ICheckRoleService checkRoleService) {
            _notesService = notesService;
            _checkRoleService = checkRoleService;
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return _checkRoleService.IsManager(User) ? View("NoteListView", _notesService.GetAllNotes()) : View("CreateNoteView");
            }
            return RedirectToAction("Login", "Account");            
            
        }

        public ActionResult NoteListView() {
            return Index();
        }

        public ActionResult CreateNoteView()
        {
            return Index();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(NoteModel item, HttpPostedFileBase upload)
        {
            try
            {
                await _notesService.AddNoteAsync(item, User.Identity.Name, upload);
            }
            catch (LimitTimeException)
            {
                ModelState.AddModelError("NoteDate", "Допускается одно сообщение в течение 24 часов");
            }
            return View("CreateNoteView");
        }

        public async Task<ActionResult> GetFile(int id)
        {
            var file = await _notesService.GetNoteFileAsync(id);
            if (file == null) return Index();
            return File(file.FileData, System.Net.Mime.MediaTypeNames.Application.Octet, file.FileName);
        }

    }
}

NoteApp/Controllers/NoteController.cs
using NoteApp.Services;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace NoteApp.Controllers
{
    public class NoteController : Controller
    {
        private readonly INotesService _notesService;

        public NoteController(INotesService notesService)
        {
            this._notesService = notesService;
        }

        public async Task SetFlag(int id, bool flag)
        {
            await _notesService.ChangeFlagAsync(id, flag);
        }

    }
}

NoteApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NoteApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NoteApp/Views/Home/CreateNoteView.cshtml
@model NoteApp.Models.NoteModel


@using (Html.BeginForm("Create", "Home", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <h4 style="color:red;">@Html.ValidationMessageFor(m => m.NoteDate)</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="file" name="upload" />
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Отправить" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

NoteApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NoteApp/Views/Home/NoteListView.cshtml
@model IEnumerable<NoteApp.Models.NoteModel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoteDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAnswered)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Topic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoteDate)
        </td>
        <td itemid="@item.Id">
            @*onclick="location.href='@Url.Action("SetFlag", "Home", new { id = item.Id, flag = item.IsAnswered })'"*@
            @Html.EditorFor(modelItem => item.IsAnswered, new { htmlAttributes = new { id = @item.Id } })
        </td>
        <td>
            @Html.ActionLink("Файл", "GetFile", new { id = item.Id })
        </td>
    </tr>
    }

</table>

@section Scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        $('.check-box').click(function (event) {
            //alert('id=' + event.target.id + ' flag=' + event.target.checked);
            $.ajax({
                    type: "GET",
                    dataType: "Json",
                    url: '@Url.Action("SetFlag", "Note")' + '?id=' + event.target.id + '&flag=' + event.target.checked,
                    async: true,
                    success: function(data) {
                        @*if (data == null || data.data == null) {
                            ErrorMessage("", "@Resource_en.YourPhoneDoesNotExistInOurDatabase");
                        } else {
                            user = data[Object.keys(data)[0]];
                                AddVereCode(user.ID);// anather Ajax call 
                                SuccessMessage("Done", "@Resource_en.VerificationCodeSentSuccessfully", "Done");
                        }*@
                    },
                    error: function() {
                        @*ErrorMessage("", '@Resource_en.ErrorOccourd');*@
                    }
                });
        });
    });
</script>

}